
SRCDIR=src
BINDIR=bin

main:
	g++ -std=c++2a \
		$(SRCDIR)/main.cpp \
		$(SRCDIR)/GraphFactory.cpp \
		$(SRCDIR)/TGraph.cpp \
		$(SRCDIR)/CompleteGraph.cpp \
		$(SRCDIR)/SimpleGraph.cpp \
		$(SRCDIR)/utils.cpp \
		$(SRCDIR)/graphUtils.cpp \
		-o $(BINDIR)/main
