
SRCDIR=src
BINDIR=bin
CFLAGS=-std=c++2a -g

main:
	g++ $(CFLAGS) \
		$(SRCDIR)/main.cpp \
		$(SRCDIR)/GraphFactory.cpp \
		$(SRCDIR)/TGraph.cpp \
		$(SRCDIR)/CompleteGraph.cpp \
		$(SRCDIR)/SimpleGraph.cpp \
		$(SRCDIR)/WeightedGraph.cpp \
		$(SRCDIR)/BipartiteGraph.cpp \
		$(SRCDIR)/utils.cpp \
		$(SRCDIR)/graphUtils.cpp \
		-o $(BINDIR)/main
